### ISSUE TITLE
releases.json breaks expected immutable version continuity

### ISSUE THREAD

**Issue by ptr727** [networkoptix/nx_open#3]
I am relying on the deterministic and immutable and forward version only change behavior of `releases.json`.

I found the change made on or about 26 Aug 2022 to `https://updates.vmsproxy.com/digitalwatchdog/releases.json` broke continuity:

- Version 4.2 was re-introduced after having been removed on or about 12 Aug 2022.
- Version 5 was downgraded from `5.0.0.35271` to `5.0.0.35138`, and the `release_date` set back to `null`.

This makes it impossible to have durable and deterministic version updates.

If the `releases.json` files are to be used for deterministic version management, I'd expect the following behaviors:

- Durable, i.e. no need to maintain history, the versions entries need to be fully inclusive at all times.
- Forward moving only, i.e. version numbers should never become smaller.
- Complete, all versions should be included, e.g. 4.2 was removed and then re-added, this should not happen.
- Release state should move forward only, e.g. the same version should not have `release_date` or `release_delivery_days` should not revert to `null` for the same version.

Here is the short history I have tacked for e.g. [DWSpectrum](https://updates.vmsproxy.com/digitalwatchdog/releases.json) showing a regression in expected versions:

1 Aug 2022:

```json
{
    "packages_urls": [
        "https://updates.networkoptix.com/digitalwatchdog",
        "http://beta.networkoptix.com/beta-builds/digitalwatchdog"
    ],
    "releases": [
        {
            "product": "vms",
            "version": "5.0.0.35271",
            "protocol_version": 5002,
            "publication_type": "release",
            "release_date": null,
            "release_delivery_days": null
        },
        {
            "product": "vms",
            "version": "4.2.0.32842",
            "protocol_version": 4201,
            "publication_type": "release",
            "release_date": "1627938214069",
            "release_delivery_days": 30
        }
    ]
}
```

12 Aug 2022 (4.2 was removed, 5.0 was released, i.e `release_date` no longer `null`):

```json
{
    "packages_urls": [
        "https://updates.networkoptix.com/digitalwatchdog",
        "http://beta.networkoptix.com/beta-builds/digitalwatchdog"
    ],
    "releases": [
        {
            "product": "vms",
            "version": "5.0.0.35271",
            "protocol_version": 5002,
            "publication_type": "release",
            "release_date": "1660167578448",
            "release_delivery_days": null
        }
    ]
}
```

26 Aug 2022 (4.2 was reintroduced, 5.0 was downgraded from `5.0.0.35271` to `5.0.0.35138`)

```json
{
    "packages_urls": [
        "https://updates.networkoptix.com/digitalwatchdog",
        "http://beta.networkoptix.com/beta-builds/digitalwatchdog"
    ],
    "releases": [
        {
            "product": "vms",
            "version": "5.0.0.35138",
            "protocol_version": 5002,
            "publication_type": "release",
            "release_date": null,
            "release_delivery_days": null
        },
        {
            "product": "vms",
            "version": "4.2.0.32842",
            "protocol_version": 4201,
            "publication_type": "release",
            "release_date": "1627938214069",
            "release_delivery_days": 30
        }
    ]
}
```

**Comment by nxmeta** [comment]
@ptr727 while I fully agree, there are some circumstances that led our release engineering team to do such changes. DW found some critical issues. And the goal was to isolate users from this upgrade. I know we could have developed it better (e.g., simply change `release_date` to `null`).

I believe what you experienced was smth exceptional (some temp issues on our side). I'll try to find out why it happened, and try to understand if it will happen moving forward.

Both disappearing and reappearing with a lower version are strange. I can only explain it with some release engineering issues we had.

But anyways, one thing to keep in mind. There would be situations when a release appears as released, with a valid release date. But after a while, it becomes invalidated (issues found, so we decided to dismiss the build). My understanding it should be done by putting the release date to null. But maybe we have several options in our internal systems and for some reason, we excluded release completely (we shouldn't have, but maybe we were forced to or it was a bug)

The downgrade is also strange. Maybe it somehow related to disappearing (e.g. we released smth wrong accidentally )

So in general I agree with all your statements, except this one:

> Release state should move forward only, e.g. the same version should not have release_date or release_delivery_days should not revert to null for the same version.

We have to be able to stop released versions from populating. E.g., if it is crashing prod systems. In general, stopping release from rolling out is common practice. release_date and release_delivery_days fields should be used for that.

**Comment by ptr727** [comment]
Thank you for replying.

Yes, I understand that bad things happen, and rolling back may be required, even if rolling forward is desired. Yet, I'd like to figure out a way to make sure that the `latest`, `stable`, `rc`, and `beta` release tags I'm trying to implement will not break.

For latest or stable tags it is not the end of the world if say 5.0.0 -> 5.0.1 -> 5.0.0, as long as it is backwards compatible.  
But for latest or stable when 4.2 -> 5.0 -> 4.2 happened (and the 5 release was completely removed from the manifest), it is a major problem as systems that upgraded to 5.0 and now returns to running 4.2 will break.  
Same would happen if e.g. a rc or beta goes to release and then suddenly back to rc or beta, all systems that follow latest or stable tags will break.

As for `release_date` and `release_delivery_days`, the [logic](https://github.com/networkoptix/nx_open/issues/2) is not clear.  
Could you describe what the correct interpretation of the values would be to correctly determine a latest and stable release, and where a major version once released may never roll back to a lesser version?

**Comment by ptr727** [comment]
https://en.wiktionary.org/wiki/abandon_hope_all_ye_who_enter_here
