### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Revan1985** [networkoptix/nx_open#6]
Hello,
I am trying to build the nx_open with vs2022, but, running build.bat at certain point broke.
This error occours:

`
customization/1.0: Not found in local cache, looking in remotes...
customization/1.0: Trying with 'nx'...
ERROR: Failed requirement 'customization/1.0' from 'conanfile.py'
ERROR: HTTPSConnectionPool(host='artifactory.nxvms.dev', port=443): Max retries exceeded with url: /artifactory/api/conan/conan/v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

Unable to connect to nx=https://artifactory.nxvms.dev/artifactory/api/conan/conan
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
CMake Error at D:/source/repos/Revan1985/nx_open-build/run_conan.cmake:96 (message):
  Conan failed to install dependencies.
Call Stack (most recent call first):
  D:/source/repos/Revan1985/nx_open-build/run_conan.cmake:128 (run_conan)

CMake Error at cmake/utils.cmake:419 (message):
  Conan execution failed.

  Command:
  "C:/Users/davide/AppData/Local/Programs/Python/Python312/Lib/site-packages/cmake/data/bin/cmake.exe
  -DinstallSystemRequirements=OFF -DconanUpdateMode=min -P
  D:/source/repos/Revan1985/nx_open-build/run_conan.cmake"

  Exit status or error message: "1"
Call Stack (most recent call first):
  cmake/conan_utils.cmake:133 (nx_execute_process_or_fail)
  cmake/conan_dependencies.cmake:56 (nx_run_conan)
  CMakeLists.txt:65 (include)

-- Configuring incomplete, errors occurred!`

Seems like https://artifactory.nxvms.dev/artifactory/api/conan/conan have a broken ssl (opening from browser shows same error, net::ERR_CERT_AUTHORITY_INVALID

**Comment by Grey-DeMonstr** [comment]
@Revan1985 Certificate is valid. The problem may be caused by out of date OS and old Trusted Root certificates. Please ensure you have the supported OS and all the latest updates installed.
